{% set version = "0.37" %}

package:
  name: antiword
  version: {{ version }}

source:
  git_url: https://github.com/sdrobert/antiword.git
  git_depth: 1

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake >=3.10
    - make  # [not win]
    - ninja  # [win]

test:
  commands:
    - antiword -h


about:
  license: GPL-2.0
  summary: 'An antiword port'
  dev_url: https://github.com/sdrobert/antiword